### PR TITLE
WPF GUI without propriety resources and using .NET 4.0

### PR DESCRIPTION
**Pull request by kiangtengl**
Tried my best to maintain .NET 4.0 compatibility. Maybe you could try compiling it now?

### CODE REVIEW

**Comment by DatZach** [comment]
I'll check it out as soon as possible, thanks.

**Comment by DatZach** [comment]
Finally managed to compile it, looks great, I'm worried about backwards compatibility though.
Any idea if this can run on systems with Windows Vista or lower?

**Comment by kiangtengl** [comment]
Not using any special apis or anything. XP with .NET 4.0 should be able to
run it. Maybe need to bundle the framework as XP does not come with .NET by
default. Only Vista and onwards has it.

On 16 July 2013 04:51, Zach Reedy notifications@github.com wrote:

> Finally managed to compile it, looks great, I'm worried about backwards
> compatibility though.
> Any idea if this can run on systems with Windows Vista or lower?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/DatZach/CharacterEditor/pull/4#issuecomment-21002655
> .

## 

Yours Sincerely,
Lim Kiang Teng
M11605
NUS High School of Math and Science

**Comment by kiangtengl** [comment]
Updated Icons. I've also made sure not to modify any files within your project, so pulling my commits should be safe.

untitled

**Comment by DatZach** [comment]
Ah, thanks. I'm going to go ahead and merge your current repo, I'll merge again later once you've completed everything else.

**Comment by DatZach** [comment]
Just so you know, in the newest commit "Restructured project" I had to remove your WPF source due to issues in the restructure, if you sync with the latest branch I'll remerge.

**Comment by kiangtengl** [comment]
Synced but can't compile. 

Could not load file or assembly 'System.Data.SQLite.dll' or one of its dependencies. The specified module could not be found.

CharacterEditor
   at CharacterEditor.Database.Load(String filename)
   at CharacterEditor.Forms.LoadCharacter.DatabaseLoad(String filename) in c:\Users\KiangTeng\Dropbox\Programming\CharacterEditor\Source\Forms\LoadCharacter.cs:line 66

Going to wait this out until the project stabilizes a bit, understand you're still in the process of refactoring.

**Comment by ghost** [comment]
http://system.data.sqlite.org/downloads/1.0.87.0/sqlite-netFx40-static-binary-bundle-Win32-2010-1.0.87.0.zip
^ Use the interop from here. ^
Make sure to either replace or delete the existing reference and add the new one. But I assume you know that. ;)
This is ESnowden from the forums and IRC by the way.

**Comment by kiangtengl** [comment]
I think both of you are using 32bit, thats why. Thanks for the pointer though!

**Comment by DatZach** [comment]
Hm, I was afraid this would happen. I think it's trying to load System.Data.SQLite.Interlop.dll, can you verify what module it is? I'm using 64bit, everything is compiled as 32bit though.

**Comment by ghost** [comment]
I am in fact on 64bit windows, but since the default compile target is x86, it is needed to use a 32bit System.Data.SQLite.dll Or you can just change to x64 and copy over the defaults from x86. Either way works.
Maybe consider providing both target DLL's? Then copy the build target to 64-bit and adjust the reference accordingly?

**Pull request merged**
